[build-system]
requires = [
    "cython>=3.0.10",
    "numpy>=1.24.4",
    "setuptools>=77.0.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "dmri-dicelib"
version = "1.4.0"
dependencies = [
    "cython>=3.0.10",
    "nibabel>=5.2.1",
    "numpy>=1.24.4",
    "psutil>=5.9.8",
    "pywin32>=306; sys_platform=='win32'",
    "scipy>=1.10.1",
    "dmri-amico>=2.0.1",
    "numpydoc>=1.7.0"
]
requires-python = ">=3.8"
authors = [
    {name = "DICE Lab", email = "DICE_lab@strutture.univr.it"}
]
maintainers = [
    {name = "DICE Lab", email = "DICE_lab@strutture.univr.it"}
]
description = "Software library of the DICE Lab (Diffusion Imaging and Connectivity Estimation Laboratory)"
readme = "README.md"
license = "LicenseRef-Proprietary"
license-files = ["LICENSE"]
keywords = [
    "Neuroimaging"
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Programming Language :: C++",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]

[project.urls]
Homepage = "https://github.com/dice-lab-vr/dicelib.git"
Documentation = "https://github.com/dice-lab-vr/dicelib/blob/master/README.md"
Repository = "https://github.com/dice-lab-vr/dicelib.git"
Issues = "https://github.com/dice-lab-vr/dicelib/issues"
Changelog = "https://github.com/dice-lab-vr/dicelib/blob/master/CHANGELOG.md"

[project.scripts]
dice_image_extract = "dicelib.scripts.dice_image:image_extract"
dice_tractogram_assign = "dicelib.scripts.dice_tractogram:assign"
dice_tractogram_cluster = "dicelib.scripts.dice_tractogram:cluster"
dice_tractogram_coherence = "dicelib.scripts.dice_tractogram:coherence"
dice_tractogram_filter = "dicelib.scripts.dice_tractogram:filter"
dice_tractogram_info = "dicelib.scripts.dice_tractogram:info"
dice_tractogram_join = "dicelib.scripts.dice_tractogram:join"
dice_tractogram_lengths = "dicelib.scripts.dice_tractogram:lengths"
dice_tractogram_locate = "dicelib.scripts.dice_tractogram:locate"
dice_tractogram_resample = "dicelib.scripts.dice_tractogram:resample"
dice_tractogram_sample = "dicelib.scripts.dice_tractogram:sample"
dice_tractogram_sanitize = "dicelib.scripts.dice_tractogram:sanitize"
dice_tractogram_shuffle = "dicelib.scripts.dice_tractogram:shuffle"
dice_tractogram_smoothPoly = "dicelib.scripts.dice_tractogram:smoothPoly"
dice_tractogram_smoothSplines = "dicelib.scripts.dice_tractogram:smoothSplines"
dice_tractogram_sort = "dicelib.scripts.dice_tractogram:sort"
dice_tractogram_split = "dicelib.scripts.dice_tractogram:split"
dice_tractogram_tdi = "dicelib.scripts.dice_tractogram:tdi"
dice_connectome_build = "dicelib.scripts.dice_connectome:build"
#dice_tractogram_recompute_indices = "dicelib.scripts.dice_tractogram:recompute_indices"
#dice_tractogram_compress = "dicelib.scripts.dice_tractogram:compress"
#dice_tractogram_convert = "dicelib.scripts.dice_tractogram:convert"
#dice_tsf_create = "dicelib.scripts.dice_tsf:create"
#dice_tsf_join = "dicelib.scripts.dice_tsf:join"

[tool.setuptools]
packages = [
    "dicelib",
    "dicelib.scripts"
]
include-package-data = false

[tool.cibuildwheel]
build-verbosity = 3
